version: '3.8'

services:
  # --- 1. BASE DE DATOS ---
  mongo:
    image: mongo:latest
    container_name: axio_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - axio-net

  # Visor de Base de Datos
  mongo-express:
    image: mongo-express
    container_name: axio_admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo
    networks:
      - axio-net

  # Caché Redis
  redis:
    image: redis:alpine
    container_name: axio_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - axio-net

  # --- 2. BACKEND (API) ---
  backend:
    build: ../../server
    container_name: axio_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/axio_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ../../server/uploads:/app/uploads
    networks:
      - axio-net

  # --- 3. FRONTEND (WEB) ---
  frontend:
    build: ../../client
    container_name: axio_frontend
    restart: always
    # CAMBIO: Usamos puerto 8080 para evitar conflictos con Skype/Windows
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - axio-net

  # --- 4. AUTOMATIZACIÓN (n8n) ---
  n8n:
    image: n8nio/n8n
    container_name: axio_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=axio_automation
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - axio-net

volumes:
  mongo_data:
  n8n_data:

networks:
  axio-net:
    driver: bridge